### ISSUE TITLE
Please add LICENSE

### ISSUE THREAD

**Issue by gmacario** [CirrusComputing/EnterpriseLibre#1]
I could not find any license file in the codebase.

See http://choosealicense.com/

**Comment by nimesh-jethwa** [comment]
Added. All the code is licensed under GPL3.

**Comment by CirrusOpen** [comment]
Cool, thanks.

On Wed, 2015-12-16 at 18:17 -0800, Nimesh Jethwa wrote:

> Closed #1.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

William (Bill) Stewart
http://CirrusComputing.com/ 
wstewart@cirruscomputing.com

## 1.613.797.7744
